spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER_NAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl-auto: validate
        default_schema: "dev"
        default_batch_fetch_size: 500
    open-in-view: false

  flyway:
    enabled: true
    baseline-on-migrate: true

book-info-client:
  default-service-name: "Aladin"
  national-library:
    cert-key: ${NATIONAL_LIBRARY_API_KEY}
    service-name: "NationalLibraryOfKorea"
  aladin:
    service-name: "Aladin"
    ttb-key: ${ALADIN_API_KEY}

gemini-client:
  api-key: ${GEMINI_API_KEY}
  parse-chapter-prompt-template: |
    HTML 형식의 목차 텍스트에서 1차 챕터 제목을 찾아, 다음과 같은 형식으로 변환해줘. number는 순서, name은 챕터 제목이야.

    [
      {
        "chapterNumber": 1,
        "name": "1장 오브젝트와 의존관계"
      },
      {
        "chapterNumber": 2,
        "name": "2장 테스트"
      },
      ...
    ]